name = "fluentai-api"
main = "src/index.js"
compatibility_date = "2025-11-09"

[ai]
binding = "AI"
remote = true

[[durable_objects.bindings]]
name = "FLUENT_STATE"
class_name = "FluentState"

[[migrations]]
tag = "v1"
new_classes = [ "FluentState" ]
